### ISSUE TITLE
Add a pre-commit config

### ISSUE THREAD

**Issue by Goldziher** [gustavopch/tsc-files#77]
Hi, thanks for this helpful tool. 

Could you add a pre-commit hook? https://pre-commit.com/#new-hooks?

P.S. this is what I use now in my `.pre`
```yaml
repos:
    - repo: local
      hooks:
          - id: typecheck
            name: typecheck
            entry: pnpm run typecheck
            require_serial: true
            language: system
            types: [javascript]
            files: ^frontend/
```

**Comment by gustavopch** [comment]
Hi. Not sure where that would be added, how that would work, what it would solve, etc.

**Comment by Goldziher** [comment]
> Hi. Not sure where that would be added, how that would work, what it would solve, etc.

This allows running the tool using the pre-commit orchestrator, which is often used in monorepos

**Comment by gustavopch** [comment]
But isn't that something you have to do in your repo rather than something that should be provided by each tool you use?

**Comment by Goldziher** [comment]
pre-commit allows tools to exposure a default configuration. its a polyglot tool, here is an example config which shows how working with both python and node:

```yaml
repos:
    # Git commit linting
    - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: "v9.22.0"
      hooks:
          - id: commitlint
            stages: [commit-msg]
            additional_dependencies: ["@commitlint/config-conventional"]

    # Shared
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-toml
          - id: check-json
          - id: check-case-conflict
          - id: name-tests-test
            args:
                - --pytest
            files: ^backend/tests
            exclude: ^backend/tests/factories|^backend/tests/test_utils|^backend/tests/completion.py|^backend/tests/test_data|^backend/tests

    - repo: https://github.com/JoC0de/pre-commit-prettier
      rev: v3.5.3
      hooks:
          - id: prettier
            exclude: ^.idea|^backend/alembic|^.git

    - repo: https://github.com/codespell-project/codespell
      rev: v2.4.1
      hooks:
          - id: codespell
            exclude: ^backend/tests
            additional_dependencies: ["tomli"]

    # Frontend
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v9.24.0
      hooks:
          - id: eslint
            files: \.[jt]sx?$
            types: [file]
            args: ["--fix", "--max-warnings=0", "--no-warn-ignored", "--cache"]
            additional_dependencies:
                [
                    "@eslint/compat",
                    "@eslint/eslintrc",
                    "@eslint/js",
                    "@next/eslint-plugin-next",
                    "eslint",
                    "eslint-plugin-jsx-a11y",
                    "eslint-plugin-markdown",
                    "eslint-plugin-n",
                    "eslint-plugin-perfectionist",
                    "eslint-plugin-promise",
                    "eslint-plugin-react",
                    "eslint-plugin-react-hooks",
                    "eslint-plugin-react-perf",
                    "eslint-plugin-unicorn",
                    "eslint-plugin-unused-imports",
                    "eslint-plugin-vitest",
                    "globals",
                    "next",
                    "react",
                    "typescript",
                    "typescript-eslint",
                ]

    # Backend
    - repo: https://github.com/Goldziher/uncomment
      rev: v1.0.4
      hooks:
          - id: uncomment
            exclude: ^frontend/next-env.d.ts

    - repo: https://github.com/tox-dev/pyproject-fmt
      rev: v2.5.1
      hooks:
          - id: pyproject-fmt
            files: ^pyproject.toml
            additional_dependencies: ["tomli"]

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.11.5
      hooks:
          - id: ruff
            args: [--fix, --unsafe-fixes]
            files: ^backend/
          - id: ruff-format
            files: ^backend/

    - repo: local
      hooks:
          - id: mypy
            name: mypy
            entry: uv run --project backend mypy
            require_serial: true
            language: system
            types: [python]
            files: ^backend/

    - repo: local
      hooks:
          - id: typecheck
            name: typecheck
            entry: cd frontend && pnpm run typecheck
            require_serial: true
            language: system
            files: ^frontend/.*\.(?:m|c)?tsx?$

```

Note two things here - there are configs for eslint, prettier etc.
